#!/bin/bash
# sign-notarize.sh — Sign + Notarize a macOS .app or .dmg for distribution
#
# Usage:
#   ./scripts/sign-notarize.sh <path-to-app-or-dmg>
#
# Env:
#   SIGN_IDENTITY   SHA-1 or full name of Developer ID Application cert.
#                   Defaults to the Gridex production cert (16/4/26, team W3C6S577FM).
#   NOTARY_PROFILE  notarytool keychain profile name (default: gridex-notarize).
#   SKIP_SIGN=1     Skip resigning (useful when already signed, just notarize).
#
# Flow:
#   .app → sign (inside-out if Sparkle present) → zip → submit → wait → staple → verify
#   .dmg → sign → submit → wait → staple → verify

set -euo pipefail

if [ -z "${1:-}" ]; then
    echo "Usage: $0 <path-to-app-or-dmg>"
    exit 1
fi

TARGET="$1"

if [ ! -e "$TARGET" ]; then
    echo "✗ Not found: $TARGET"
    exit 1
fi

# SIGN_IDENTITY: SHA-1 fingerprint or common name of your Developer ID Application cert.
# Not a secret — certs are public. Set via .env or export before running.
# Fall back to "-" (ad-hoc) if unset, so forks can build without an Apple account.
SIGN_IDENTITY="${SIGN_IDENTITY:-${GRIDEX_SIGN_IDENTITY:-}}"
if [ -z "$SIGN_IDENTITY" ] && [ -f "$(dirname "$0")/../.env" ]; then
    SIGN_IDENTITY=$(grep -E "^SIGN_IDENTITY=" "$(dirname "$0")/../.env" | cut -d= -f2- | tr -d '"')
fi
if [ -z "$SIGN_IDENTITY" ]; then
    echo "✗ SIGN_IDENTITY not set. Set it in .env or export it:"
    echo "    echo 'SIGN_IDENTITY=<your-sha1-or-cert-name>' >> .env"
    echo "  Find your cert with: security find-identity -v -p codesigning"
    exit 1
fi

NOTARY_PROFILE="${NOTARY_PROFILE:-gridex-notarize}"
SKIP_SIGN="${SKIP_SIGN:-0}"

echo "═══════════════════════════════════════════"
echo "  Sign + Notarize"
echo "  Target:   $TARGET"
echo "  Identity: $SIGN_IDENTITY"
echo "  Profile:  $NOTARY_PROFILE"
echo "═══════════════════════════════════════════"

EXT="${TARGET##*.}"

sign_app() {
    local app="$1"

    # Inside-out: if Sparkle.framework is embedded, sign its nested helpers first
    local sparkle="$app/Contents/Frameworks/Sparkle.framework"
    if [ -d "$sparkle/Versions/B" ]; then
        echo "→ Signing Sparkle helpers (inside-out)..."
        codesign --force --options runtime --timestamp \
            --sign "$SIGN_IDENTITY" \
            "$sparkle/Versions/B/Autoupdate" \
            "$sparkle/Versions/B/Updater.app" 2>&1 | grep -v "unsealed contents" || true
        codesign --force --options runtime --timestamp \
            --sign "$SIGN_IDENTITY" \
            "$sparkle" 2>&1 | grep -v "unsealed contents" || true
    fi

    # Entitlements live alongside the runtime (generated by build-app.sh)
    local ent_arg=""
    local runtime_ent="$(dirname "$app")/runtime.entitlements"
    if [ -f "$runtime_ent" ]; then
        ent_arg="--entitlements $runtime_ent --generate-entitlement-der"
    fi

    echo "→ Signing app bundle..."
    local cs_output
    # shellcheck disable=SC2086
    cs_output=$(codesign --force --deep --options runtime --timestamp \
        --sign "$SIGN_IDENTITY" \
        $ent_arg \
        "$app" 2>&1) || {
            echo "✗ codesign failed"
            echo "$cs_output"
            exit 1
        }
    echo "$cs_output" | grep -v "unsealed contents" || true
}

verify_app() {
    local app="$1"
    echo "→ Verifying signature..."
    codesign --verify --deep --strict --verbose=2 "$app"
    echo "→ Checking Gatekeeper assessment (pre-notarize, may reject — OK)..."
    spctl -a -t exec -vv "$app" 2>&1 || true
}

notarize() {
    local archive="$1"
    echo "→ Submitting to Apple Notary Service (5-15 min)..."
    xcrun notarytool submit "$archive" \
        --keychain-profile "$NOTARY_PROFILE" \
        --wait
}

if [ "$EXT" = "app" ]; then
    APP_PATH="$TARGET"

    if [ "$SKIP_SIGN" != "1" ]; then
        sign_app "$APP_PATH"
    fi
    verify_app "$APP_PATH"

    ZIP_PATH="$(dirname "$APP_PATH")/$(basename "$APP_PATH" .app).zip"
    echo "→ Creating zip for notarization..."
    rm -f "$ZIP_PATH"
    ditto -c -k --keepParent "$APP_PATH" "$ZIP_PATH"

    notarize "$ZIP_PATH"
    rm -f "$ZIP_PATH"

    echo "→ Stapling notarization ticket..."
    xcrun stapler staple "$APP_PATH"

    echo "→ Final Gatekeeper check..."
    spctl -a -t exec -vv "$APP_PATH"

    echo ""
    echo "✓ Done: $APP_PATH"

elif [ "$EXT" = "dmg" ]; then
    DMG_PATH="$TARGET"

    if [ "$SKIP_SIGN" != "1" ]; then
        echo "→ Signing DMG..."
        codesign --force --sign "$SIGN_IDENTITY" --timestamp "$DMG_PATH"
    fi

    notarize "$DMG_PATH"

    echo "→ Stapling notarization ticket..."
    xcrun stapler staple "$DMG_PATH"

    echo "→ Final Gatekeeper check..."
    spctl -a -t open --context context:primary-signature -vv "$DMG_PATH"

    echo ""
    echo "✓ Done: $DMG_PATH"

else
    echo "✗ Target must be .app or .dmg (got .$EXT)"
    exit 1
fi
